### PR TITLE
fix LDoc annotation

### PR DESCRIPTION
**Pull request by sharpchen**
## Code sample

```lua
---@alias Record table<string, any>
---@type Record
local t = {
    key = 'value'
}
--- merge two tables
---@param this table
---@param other table
---@return table
table.merge = function(this, other)
    for key, value in pairs(other) do
        if not this[key] then
            this[key] = value
        end
    end
    return this
end
```

## Scopes

- `support.type.lua`
- `storage.type.annotation.lua`

## Screenshots

|before|after|
|---|---|
|after|before|

### CODE REVIEW

**Comment by fisheva** [comment]
Does it mean they are `Class` not `Data type` ?

**Comment by sharpchen** [comment]
LDoc is similar to jsdoc, can define type alias in comment. The `table` is the built-in type structure in lua, but the identifier can be any custom type defined in LDoc. Since textmate for lua doesn't provide more detailed rules for built-in type(like `table`, `string`) and I do think color for types has a wider range for this, so I made it like so.

**Comment by sharpchen** [comment]
And I'm currently developing the Eva-Theme for Neovim and I apologize for not seeking permission beforehand. If you believe it's not the appropriate time or I'm not the right person for this, I will remove the repository.

**Comment by fisheva** [comment]
I'm sorry! I haven't replied to your first reply about the Neovim version yet. I didn't even notice that it was you, I'm so sorry!

I originally planned to reply to you there after I figured out how to synchronize the organization and personal repository. I'm trying these days after work.

I want to say, of course, you can! From the historical pull requests you submitted, I can see your meticulousness and seriousness. I feel so happy and honored to have gained a teammate like you!

**Comment by fisheva** [comment]
I asked ChatGPT about how to synchronize organizational and personal repository and tried following the steps it told me, but it has failed so far. 
WX20240520-220613@2x

When I clicked on this workflow record, it went to the "Oops! 500" page. I am planning to consult Github customer service.
WX20240520-220821@2x

**Comment by fisheva** [comment]
The content of this pull request has been updated to version 2.6.3. 

When I successfully complete the workflow of automatically synchronizing organizational and personal repositories, I will open a Neovim version repository in the Eva Theme organization and organize my synchronization process into a document, telling you how to operate it. Wait my news, thanks!

**Comment by fisheva** [comment]
If you have prepared the preliminary version of Eva Theme for Neovim and released it in Neovim's plugin market, you can send me the plugin link and I will write it into README.
WX20240520-231210@2x

**Comment by sharpchen** [comment]
Ok, good to hear that. I'm going to style bold, italic and italic bold variants now, I wonder:

- What kind of keyword or identifier are expected to be bold
- What kind of keyword or identifier are expected to be italic
- What kind of keyword or identifier are expected to be bold and italic
- Is there any difference for token colors between italic/bold/italic-bold and normal variant?

**Comment by fisheva** [comment]
I updated a new document: [font-style-rules](https://github.com/fisheva/Eva-Theme/blob/master/documents/font-style-rules.md).

All token colors are the same in all variants.

**Comment by sharpchen** [comment]
should key word operator like `and`/`or` in some languages be italic or bold?

**Comment by fisheva** [comment]
In bold variant, `and`/`or` are bold.
In italic variant, `and`/`or` are italic.

**Comment by fisheva** [comment]
I posted a question on the Github community: [How to Automatically Sync Personal and Organization Repositories Using GitHub Actions?](https://github.com/orgs/community/discussions/125704)

**Comment by sharpchen** [comment]
I just done the first release :)

> If you have completed the preliminary version of Eva Theme for Neovim and released it in Neovim's plugin market, you can send me the plugin link and I will write it into README.

NeoVim doesn't have any plugin market, github itself is the place we fetch plugins, so a repository link is suffice.

**Comment by fisheva** [comment]
Great! Your links has been here.
企业微信截图_20240528185743

**Pull request merged**
